project_id = "iwvpbnhsabnioxrlddqx"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.backtest-callback]
    verify_jwt = false
  [functions.tv-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.request-password-reset]
    verify_jwt = false

