-- Tier 1: ORB
INSERT INTO public.lessons (title, description, module, module_order, tier_required, content_type, author_id, is_published, estimated_minutes, slides) VALUES
('Opening Range Breakout — The Setup', 'Learn the ORB strategy from first principles — what it is, why it works, and how to identify the setup.', 'tier1_orb', 1, 'tier1', 'platform', NULL, true, 15, '[
  {"id":"s1","title":"What is the Opening Range?","body":"The Opening Range (OR) is the high and low of the first 5-minute candle after the 9:30 AM ET market open. This single candle captures the initial battle between overnight positions unwinding, institutional orders executing, and retail traders reacting to the open. The range it creates often defines the boundaries for the entire morning session.","bullet_points":["The OR forms between 9:30 and 9:35 AM ET","Mark the high with a horizontal line","Mark the low with a horizontal line","These two lines are your breakout levels for the session"],"tip":"In TradingGYM''s simulator, the blueprint overlay will prompt you to mark these lines. Practice until it becomes automatic — you should be able to mark the OR in under 5 seconds."},
  {"id":"s2","title":"Why ORB works","body":"The ORB strategy works because the opening range acts as a compression zone. Large institutional orders create a defined range, and when price breaks out of that range with conviction, it signals that one side has won the opening battle. The move that follows often carries momentum as stops get triggered and new orders pile in.","bullet_points":["Institutional orders cluster at the open — creating the range","A breakout signals one side has overwhelmed the other","Stop orders beyond the range add fuel to the breakout move","The strategy has been used by professional traders for decades"],"tip":"ORB does not work every day. Some days the range is too wide (no clear compression) or too narrow (false breakouts). Learning to filter is what separates Tier 1 from Tier 2."},
  {"id":"s3","title":"Identifying a valid ORB range","body":"Not every opening range produces a tradeable breakout. The range needs to be the right size — too wide and your stop loss becomes too large, too narrow and the breakout is likely to fail. For MES futures, a range between 0.3% and 1.0% of the current price is ideal.","bullet_points":["Measure the range: OR high minus OR low","Calculate as percentage of price: (range / price) × 100","0.3% to 1.0% = ideal range for MES","Below 0.3% = too narrow, high false breakout risk","Above 1.0% = too wide, stop loss too expensive"],"tip":"If the range is outside the ideal zone, skip the session. Not trading IS a valid decision. The best traders know when to sit out."},
  {"id":"s4","title":"The breakout candle","body":"A valid breakout occurs when a full 5-minute candle body closes completely above the OR high (bullish breakout) or completely below the OR low (bearish breakout). Wicks do not count — only the body. This is the single most important rule in ORB and the one traders violate most often.","bullet_points":["BODY must close above OR high (long) or below OR low (short)","Wicks piercing the level do NOT count as breakouts","The breakout candle should have a strong close (near its extreme)","A weak close (long wick in the breakout direction) is a warning sign"],"tip":"This is where most beginners fail — they enter on a wick above the range and get stopped out when the candle closes back inside. Wait for the close. Always."},
  {"id":"s5","title":"What comes next","body":"Now you know how to identify the setup. In the next lesson, you will learn the full 6-step execution blueprint — from marking the range through to executing the trade and reviewing the result. Every step builds on what you just learned.","tip":"Open the simulator after this lesson and practice marking opening ranges on historical data. Do not worry about trading yet — just mark the range on 10 different days and note the size."}
]'::jsonb),
('Opening Range Breakout — The 6-Step Blueprint', 'Master the complete ORB execution sequence — from marking the range to reviewing your trade.', 'tier1_orb', 2, 'tier1', 'platform', NULL, true, 20, '[
  {"id":"s1","title":"Step 1: Mark the Opening Range","body":"At exactly 9:35 AM ET, the first 5-minute candle has closed. Draw a horizontal line at the high and another at the low. These are your breakout levels. Also mark the midpoint — this will be your stop loss reference.","bullet_points":["Use the horizontal line tool (shortcut: H)","Top line = OR High","Bottom line = OR Low","Midpoint = (High + Low) / 2 — your stop loss level"],"tip":"Label your lines. In TradingGYM, use the text tool (shortcut: L) to label ''OR High'', ''OR Low'', and ''Midpoint''. This builds the habit of organized chart markup."},
  {"id":"s2","title":"Step 2: Wait for breakout","body":"After marking the range, wait. Do nothing until a full 5-minute candle body closes completely outside the range. This is the hardest step because it requires patience. Most losing ORB trades come from entering too early — on a wick, on the breakout candle itself, or on ''anticipation'' before the close.","bullet_points":["Watch subsequent 5-minute candles","Bullish breakout: body closes ABOVE the OR High line","Bearish breakout: body closes BELOW the OR Low line","No breakout by 10:00 AM? Consider skipping the session"],"tip":"Set a timer for 10:00 AM. If no valid breakout has occurred by then, the ORB setup is dead for the day. Move on."},
  {"id":"s3","title":"Step 3: Wait for retest","body":"After a valid breakout, do NOT enter immediately. Wait for price to pull back and retest the broken level. In a bullish breakout, wait for price to come back down to the OR High area. This pullback is called the retest, and it gives you a better entry with a tighter stop.","bullet_points":["Bullish: wait for price to pull back toward OR High","Bearish: wait for price to rally back toward OR Low","The retest may take 1-3 candles to develop","No retest within 15 minutes? The move may be too strong — skip it"],"tip":"About 70% of valid breakouts produce a retest. The 30% that do not are the ones that run hard and fast. It is better to miss a trade than to chase one."},
  {"id":"s4","title":"Step 4: Confirm the retest","body":"The retest candle must wick into the range but close back outside it. This confirms that the breakout level has flipped — old resistance became new support (bullish) or old support became new resistance (bearish). If the retest candle closes back inside the range, the breakout has failed. Do not trade.","bullet_points":["Valid retest: wick touches the level, body closes outside the range","Failed retest: body closes back inside the range — no trade","The close of the retest candle is your entry signal","A strong retest close (near its extreme) is ideal"],"tip":"This step filters out about half of all breakout attempts. That is by design — you only want the ones that work."},
  {"id":"s5","title":"Step 5: Set targets","body":"Before entering the trade, set your stop loss and take profit. Stop loss goes at the midpoint of the opening range — this is roughly 50% of the OR width. Take profit goes at 2:1 R:R from your entry. Both must be set BEFORE you click the entry button. No exceptions.","bullet_points":["Stop loss = OR midpoint (50% of range width)","Risk = distance from entry to stop loss","Take profit = entry + (2 × risk) for longs, entry - (2 × risk) for shorts","Verify: is the risk within your 2% daily max?"],"tip":"In the simulator, drag the SL and TP lines to these levels. The P&L calculator will show you the exact risk in dollars before you execute."},
  {"id":"s6","title":"Step 6: Execute and review","body":"Enter at market on the close of the retest confirmation candle. Then do nothing — let the trade work. Do not move your stop loss. Do not take early profits. Let price hit your TP or your SL. After the trade closes, record the result and note one thing you did well and one thing you can improve.","bullet_points":["Enter at market — do not use limit orders for ORB","Do not touch your stop loss after entry","Let the trade hit TP or SL — no manual exits","Record: entry price, exit price, result, one lesson learned"],"tip":"The review step is where real improvement happens. TradingGYM tracks your trades automatically — use the Analytics page to spot patterns in your wins and losses."}
]'::jsonb),
('Opening Range Breakout — Common Mistakes', 'Learn the mistakes that cause most ORB losses — and how to avoid them.', 'tier1_orb', 3, 'tier1', 'platform', NULL, true, 10, '[
  {"id":"s1","title":"Entering on the breakout candle","body":"The most common ORB mistake is entering the moment price breaks the range instead of waiting for the retest. This feels right because you are ''catching the move early'' — but in practice, about 40% of initial breakouts fail and reverse back into the range. The retest filter cuts your loss rate nearly in half.","tip":"If you find yourself entering on the breakout candle, add ''Wait for retest'' as the FIRST item on your pre-trade checklist. Make it impossible to skip."},
  {"id":"s2","title":"Trading a range that is too wide or too narrow","body":"A narrow range (below 0.3% of price) produces breakouts that are just noise — random fluctuation, not institutional momentum. A wide range (above 1.0%) means your stop loss at the midpoint is too far away, destroying your R:R ratio. Both scenarios lead to losses.","bullet_points":["Too narrow: false breakouts, getting whipsawed in and out","Too wide: stop loss too expensive, bad R:R ratio","Solution: measure the range before looking for a breakout","If it is outside 0.3–1.0%, do not trade ORB today"]},
  {"id":"s3","title":"Moving your stop loss","body":"After entering a trade, the temptation to move your stop loss further away is overwhelming when price moves against you. Do not do it. Your stop was placed at the midpoint for a reason — if price reaches it, the setup has failed. Moving the stop turns a small, planned loss into a large, unplanned one.","tip":"Every time you move a stop loss further away, you are telling the market ''I was wrong about the setup but I refuse to accept it.'' The market does not care about your feelings."},
  {"id":"s4","title":"Overtrading after a loss","body":"You took a valid ORB trade, followed every step, and still lost. That is normal — even the best ORB implementation has a 40-50% loss rate. The mistake is taking a second ORB trade immediately to ''make it back.'' ORB produces one setup per day. One. If it fails, your session is over.","bullet_points":["ORB = one trade per day maximum","A loss on a valid setup is not a mistake — it is expected","A second trade to recover IS a mistake — it is revenge trading","Hit your daily max loss? Stop. Come back tomorrow."],"tip":"Log your emotional state after every loss. Over time, you will see that your worst days are the ones where you traded after hitting your limit."}
]'::jsonb);

-- Tier 2: VWAP
INSERT INTO public.lessons (title, description, module, module_order, tier_required, content_type, author_id, is_published, estimated_minutes, slides) VALUES
('VWAP — The Institutional Anchor', 'Understand VWAP and how it transforms your ORB trading with directional context.', 'tier2_vwap', 1, 'tier2', 'platform', NULL, true, 15, '[
  {"id":"s1","title":"What is VWAP?","body":"VWAP (Volume Weighted Average Price) is the average price of an instrument weighted by volume throughout the trading day. It resets at the start of each session. Institutional traders use VWAP as a benchmark — they consider buying below VWAP a good fill and selling above VWAP a good fill. This creates a gravitational pull around the VWAP line.","bullet_points":["VWAP = cumulative (price × volume) / cumulative volume","Resets daily at the session open","Institutional benchmark — real money trades around this level","Price above VWAP = bullish context, price below = bearish context"],"tip":"You do not need to calculate VWAP — TradingGYM draws it on your chart automatically when you reach Tier 2. Focus on reading it, not computing it."},
  {"id":"s2","title":"VWAP as a directional filter","body":"In Tier 1, you took ORB breakouts in both directions. In Tier 2, VWAP tells you which direction to trade. If price is above VWAP, only take long breakouts (above OR High). If price is below VWAP, only take short breakdowns (below OR Low). This single filter eliminates about half of your losing trades because it keeps you aligned with institutional flow.","bullet_points":["Price above VWAP → only trade long ORB breakouts","Price below VWAP → only trade short ORB breakdowns","Price right at VWAP → no trade — wait for clarity","Check VWAP BEFORE the breakout occurs, not after"],"tip":"This means some days you will see a valid ORB breakout and not trade it because VWAP says no. That discipline is exactly what separates profitable traders from unprofitable ones."},
  {"id":"s3","title":"VWAP reversion trades","body":"Price tends to return to VWAP during the trading day — this is called mean reversion. When price extends far above VWAP, it often pulls back toward it. When price extends far below, it often bounces back. This is not a strategy to trade yet — it is context to understand why some ORB breakouts stall and reverse.","bullet_points":["Extended above VWAP = likely to pull back","Extended below VWAP = likely to bounce","This explains why some breakouts fail despite valid setups","VWAP reversion as a standalone strategy is an advanced topic"]},
  {"id":"s4","title":"Putting it together: ORB + VWAP","body":"Your Tier 2 blueprint is the same 6-step ORB sequence from Tier 1, with one addition before Step 2: check VWAP. If VWAP does not support the breakout direction, you sit out. Every other step remains identical. You are not learning a new strategy — you are adding a filter that improves the one you already know.","bullet_points":["Step 0 (NEW): Check — is price above or below VWAP?","Step 1: Mark the Opening Range (same as Tier 1)","Step 2: Wait for breakout IN the VWAP direction only","Steps 3–6: Retest, confirm, targets, execute (same as Tier 1)"],"tip":"In the simulator, the blueprint overlay will now include the VWAP check as a step. Your step accuracy is tracked — skipping the VWAP check counts against you."}
]'::jsonb),
('VWAP in Practice — Reading Real Setups', 'Learn to read VWAP context on live charts and make better trade decisions.', 'tier2_vwap', 2, 'tier2', 'platform', NULL, true, 10, '[
  {"id":"s1","title":"VWAP slope matters","body":"A rising VWAP confirms buying pressure throughout the day. A flat VWAP suggests a range-bound day. A falling VWAP confirms selling pressure. The slope adds confidence to your directional filter — a rising VWAP with price above it is a stronger long signal than a flat VWAP with price barely above it.","bullet_points":["Rising VWAP + price above = strong bullish context","Flat VWAP + price near = no clear direction — sit out","Falling VWAP + price below = strong bearish context","Slope changes during the day — reassess at each setup"]},
  {"id":"s2","title":"When VWAP conflicts with the breakout","body":"Some days the ORB breaks out bullishly but VWAP is below price and falling. This is a conflict — the breakout says go long but VWAP says the day is bearish. In Tier 2, VWAP wins. Every time. Even when the breakout looks perfect. This will feel wrong sometimes, and you will watch profitable trades you did not take. That is the cost of the filter — and it is worth it.","tip":"Track every setup you skip because of VWAP conflict. At the end of the month, check how many of those skipped trades would have been winners. You will find that skipping saved you more than it cost you."},
  {"id":"s3","title":"Your Tier 2 edge","body":"With the VWAP filter added, your expected win rate should improve from the 50% range to 55%+. This is not a dramatic change — but at 2:1 R:R, even a 5% improvement in win rate significantly increases your monthly P&L. The graduation gate for Tier 2 requires 55% win rate across 20 trades. This is achievable if you follow the filter consistently.","tip":"Use the Analytics page to compare your Tier 1 win rate (without VWAP) to your Tier 2 win rate (with VWAP). The data should show the improvement clearly."}
]'::jsonb);

-- Tier 3: AMD + IFVG
INSERT INTO public.lessons (title, description, module, module_order, tier_required, content_type, author_id, is_published, estimated_minutes, slides) VALUES
('AMD — Accumulation, Manipulation, Distribution', 'Learn the institutional delivery model that explains why price moves the way it does.', 'tier3_amd', 1, 'tier3', 'platform', NULL, true, 20, '[
  {"id":"s1","title":"The AMD model","body":"AMD stands for Accumulation, Manipulation, Distribution. It describes how institutional traders move price through three predictable phases. Understanding this model changes how you read the chart — instead of reacting to what price is doing, you anticipate what it is about to do based on which phase you are in.","bullet_points":["Accumulation — institutions build positions quietly in a range","Manipulation — price spikes to trigger retail stops and create liquidity","Distribution — the real move begins as institutions deploy their full position","This cycle repeats on every time frame, every day"],"tip":"AMD is an ICT (Inner Circle Trader) concept. It applies to all markets and time frames, but we will focus on MES 5-minute charts at the NY open."},
  {"id":"s2","title":"Phase 1: Accumulation","body":"Accumulation looks like a boring, tight range on your chart — 3 or more candles with overlapping bodies, no new highs, no new lows. This is NOT indecision — it is institutional traders quietly building their position without moving price. They need to accumulate a large position before the move, and they do this by buying and selling in small increments within the range.","bullet_points":["3+ candles with overlapping bodies = accumulation zone","Draw a rectangle around the zone (shortcut: R)","No new high or low being made — price is coiling","The longer the accumulation, the bigger the eventual move"]},
  {"id":"s3","title":"Phase 2: Manipulation (the stop hunt)","body":"After accumulation, price spikes sharply in one direction — often the WRONG direction. This is the manipulation phase. Its purpose is to trigger stop losses above or below the range, creating liquidity that institutions need to fill their full position. Retail traders see a breakout and enter. Institutions see retail stops and use them as exit liquidity.","bullet_points":["Price breaks above or below the accumulation zone sharply","Retail traders enter on the ''breakout'' — this is the trap","Stops get triggered, providing liquidity to institutions","The sweep candle often has a long wick back into the range"],"tip":"In ORB trading (Tier 1), you waited for a retest to avoid false breakouts. In AMD, you learn WHY those false breakouts happen — they are not random, they are engineered."},
  {"id":"s4","title":"Phase 3: Distribution","body":"After the stop hunt, price reverses sharply in the opposite direction. This is distribution — institutions have accumulated their position, used the manipulation spike to fill it completely, and now they let price move to their target. This is the move you want to trade. It is often the strongest, most directional move of the session.","bullet_points":["Price reverses from the manipulation spike","The move goes in the opposite direction of the fake breakout","This is the real trade — enter after the manipulation confirms","Target: the opposite side of the accumulation zone, then beyond"]},
  {"id":"s5","title":"AMD + VWAP context","body":"AMD does not replace VWAP — it adds a layer. Use VWAP to determine the session bias (are institutions net buyers or sellers today?). Then use AMD to identify WHERE in the cycle you are. If VWAP says bullish and you see accumulation forming near VWAP, expect a downward manipulation spike followed by an upward distribution move.","tip":"This is the most complex strategy in TradingGYM. Take your time. Practice identifying AMD phases on historical charts before trading them live in the simulator."}
]'::jsonb),
('Inverse Fair Value Gap — The Entry Technique', 'Learn to identify IFVGs and use them as precision entry points within the AMD model.', 'tier3_amd', 2, 'tier3', 'platform', NULL, true, 15, '[
  {"id":"s1","title":"What is a Fair Value Gap?","body":"A Fair Value Gap (FVG) is a three-candle pattern where the middle candle''s body is so large that it creates a gap between the first candle''s wick and the third candle''s wick. This gap represents an area where price moved so fast that not all orders were filled. Price tends to return to these gaps to fill the unfilled orders.","bullet_points":["Three consecutive candles","The middle candle has a large body","Gap between candle 1 wick extreme and candle 3 wick extreme","Price tends to revisit and fill this gap"]},
  {"id":"s2","title":"Inverse Fair Value Gap (IFVG)","body":"An IFVG occurs during the manipulation phase of AMD. The stop-hunt candle creates a fair value gap as it spikes through the accumulation zone. When price reverses (starting the distribution phase), it retests this gap from the opposite side — the gap that was bearish becomes a bullish entry zone, and vice versa. This is your entry point.","bullet_points":["The manipulation spike creates an FVG","When price reverses, the FVG flips — becoming an IFVG","The IFVG is your entry zone for the distribution trade","Mark it with the rectangle tool — enter when price touches it"],"tip":"The IFVG gives you a specific price level to enter, rather than entering on a vague ''reversal signal.'' This precision is what makes Tier 3 trading more consistent than Tier 1 or 2."},
  {"id":"s3","title":"The 7-step AMD+IFVG blueprint","body":"Your Tier 3 execution sequence has 7 steps. It builds on everything you learned in Tier 1 and Tier 2.","bullet_points":["Step 1: Session bias — is price above or below VWAP?","Step 2: Identify accumulation zone — 3+ overlapping candles","Step 3: Identify liquidity target — equal highs or lows beyond the zone","Step 4: Wait for manipulation sweep — price runs the stops","Step 5: Mark the IFVG — the gap created by the sweep candle","Step 6: Enter at IFVG retest — stop beyond sweep extreme, TP at 2:1","Step 7: Record result and review — note the delivery model"]},
  {"id":"s4","title":"Stop placement and targets","body":"Your stop loss goes beyond the extreme of the manipulation sweep — if price exceeds that level, the AMD model has failed and you want to be out. Your take profit targets the opposite side of the accumulation zone first (partial), then the next liquidity pool (full exit). Minimum R:R is 2:1 — if the IFVG entry does not give you 2:1 to the first target, skip the trade.","bullet_points":["Stop loss: beyond the manipulation sweep extreme","Target 1: opposite side of accumulation zone (partial profit)","Target 2: next liquidity pool at 2:1+ R:R (full exit)","If R:R is less than 2:1, do not take the trade"]},
  {"id":"s5","title":"Mastering Tier 3","body":"AMD+IFVG is the most advanced strategy in TradingGYM. It requires pattern recognition that takes time to develop. The graduation requirement — 20 trades at 55%+ win rate — is achievable but demands patience and discipline. Use the simulator extensively. Review every trade. The Analytics page will show you which phase you struggle with most.","tip":"Many traders spend weeks on Tier 3 before hitting the graduation gate. That is normal and expected. The strategy works — but only when you can read the phases correctly. When in doubt, sit out."}
]'::jsonb);
