ALTER TABLE public.strategies
  ADD COLUMN IF NOT EXISTS range_start_time time,
  ADD COLUMN IF NOT EXISTS range_end_time time,
  ADD COLUMN IF NOT EXISTS trade_start_time time,
  ADD COLUMN IF NOT EXISTS trade_end_time time,
  ADD COLUMN IF NOT EXISTS eod_flat_time time,
  ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'America/New_York',
  ADD COLUMN IF NOT EXISTS skip_holidays boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS entry_method text DEFAULT 'on_cross',
  ADD COLUMN IF NOT EXISTS retest_entry_type text,
  ADD COLUMN IF NOT EXISTS limit_order_placement integer,
  ADD COLUMN IF NOT EXISTS retest_stop_method text,
  ADD COLUMN IF NOT EXISTS range_stop_loss_pct integer,
  ADD COLUMN IF NOT EXISTS breakout_threshold numeric,
  ADD COLUMN IF NOT EXISTS risk_per_trade numeric,
  ADD COLUMN IF NOT EXISTS stop_loss_ticks integer,
  ADD COLUMN IF NOT EXISTS take_profit_r numeric,
  ADD COLUMN IF NOT EXISTS breakeven_r numeric,
  ADD COLUMN IF NOT EXISTS max_contracts integer,
  ADD COLUMN IF NOT EXISTS trailing_stop_enabled boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS trailing_activate_r numeric,
  ADD COLUMN IF NOT EXISTS atr_length integer DEFAULT 14,
  ADD COLUMN IF NOT EXISTS atr_multiplier numeric DEFAULT 1,
  ADD COLUMN IF NOT EXISTS atr_timeframe text DEFAULT 'chart',
  ADD COLUMN IF NOT EXISTS max_long_per_day integer,
  ADD COLUMN IF NOT EXISTS max_short_per_day integer,
  ADD COLUMN IF NOT EXISTS max_wins_per_day integer,
  ADD COLUMN IF NOT EXISTS max_losses_per_day integer,
  ADD COLUMN IF NOT EXISTS use_breakout_candle_sl boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS filters jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS indicator_set jsonb DEFAULT '{}'::jsonb;